
version: '3.8'

services:
  rosch-web:
    build: .
    ports:
      - "8414:8414"
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
    restart: unless-stopped
